### ISSUE TITLE
Disable during unit tests

### ISSUE THREAD

**Issue by OakBehringer** [laravel-notification-channels/twilio#147] opened 2024-10-24 18:37 UTC
Kinda wild that there's no way to turn off api connectivity with Twilio during unit testing. Here's a solution proposed years ago that has been ignored. 

https://github.com/laravel-notification-channels/twilio/pull/121

**Comment by onlime** [comment] 2024-11-26 10:50
Duplicate of #121. I have now released [v4.0.0](https://github.com/laravel-notification-channels/twilio/releases/tag/4.0.0) with this merged, so you can use the new `TWILIO_ENABLED` env var in your `phpunit.xml` like so:

```xml
    <env name="TWILIO_ENABLED" value="false"/>
```

**Closed as completed by onlime** 2024-11-26 10:50 UTC
